name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Chạy khi có push vào nhánh main
  pull_request:
    branches:
      - main  # Chạy khi có pull request vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Phiên bản Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Chạy deploy sau khi job build thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Các lệnh deploy của bạn, ví dụ:
          # ssh user@server 'deploy-script.sh'
